---
version: '3'

vars:
  NAME: loadavg

tasks:
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt update
      # For x86-64, NASM (Netwide Assembler) is the standard
      - sudo apt install nasm build-essential gdb
  assy:
    desc: Assemble
    dir: src
    cmds:
      - nasm -f elf64 {{.NAME}}.asm -o {{.NAME}}.o
  link:
    desc: Link
    dir: src
    cmds:
      - ld {{.NAME}}.o -o {{.NAME}}
  run:
    desc: Run
    dir: src
    cmds:
      - ./{{.NAME}}
  build-run:
    desc: Assemble, link, and run the tool
    cmds:
      - task: assy
      - task: link
      - task: run
  dbg:
    desc: Assemble, link, and debug the tool
    dir: src
    cmds:
      - nasm -f elf64 -g -F dwarf {{.NAME}}.asm -o {{.NAME}}.o
      - ld {{.NAME}}.o -o amd64-sys-fetch
      - gdb ./amd64-sys-fetch
  rosetta-amd64:
    desc: Compile rosetta.c for amd64
    dir: ref
    cmds:
      - gcc -o rosetta-amd64 rosetta.c
      - gcc -S -o rosetta-amd64.s rosetta.c
  view-rosetta-asm:
    desc: View the generated assembly for rosetta.c
    preconditions:
      - sh: test -f ref/rosetta-amd64.s
        msg: "Run 'task rosetta-amd64' first to generate the assembly listing."
    cmds:
      - command -v bat > /dev/null && bat ref/rosetta-amd64.s || cat ref/rosetta-amd64.s
  default:
    cmds:
      - task -l
    silent: true
